### ISSUE TITLE
1.74.0 introduced JRuby errors with `'unescape': undefined method 'encoding' for nil:NilClass`

### ISSUE THREAD

**Issue by chadlwilson** [sass-contrib/sassc-embedded-shim-ruby#89]
Is there any reason that we'd start getting Sprockets-originated failures with `1.74.0`, seemingly related to the changes in #88 ?

Reading between the lines I have seen things that deal with URLs and relative paths in JRuby go awry before, so have a suspicion this might be JRuby specific.

```
      ActionView::Template::Error:
        Error: uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/rfc2396_parser.rb:319:in `unescape': undefined method `encoding' for nil:NilClass (NoMethodError)
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sassc-embedded-1.74.0/lib/sassc/embedded.rb:632:in `unescape'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sassc-embedded-1.74.0/lib/sassc/embedded.rb:336:in `canonicalize'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sassc-embedded-1.74.0/lib/sassc/embedded.rb:204:in `canonicalize'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.74.1/lib/sass/compiler/host/importer_registry.rb:71:in `canonicalize'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.74.1/lib/sass/compiler/host.rb:150:in `canonicalize_request'
        	from org/jruby/RubyKernel.java:2232:in `public_send'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.74.1/lib/sass/compiler/host.rb:187:in `block in await'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.74.1/lib/sass/compiler/host.rb:199:in `listen'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.74.1/lib/sass/compiler/host.rb:180:in `await'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.74.1/lib/sass/compiler/host.rb:78:in `compile_request'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.74.1/lib/sass/compiler.rb:171:in `compile_string'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.74.1/lib/sass/embedded.rb:37:in `compile_string'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sassc-embedded-1.74.0/lib/sassc/embedded.rb:18:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/dartsass-sprockets-3.1.0/lib/sassc/rails/template.rb:41:in `block in call'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/utils.rb:145:in `block in module_include'
        	from org/jruby/ext/thread/Mutex.java:171:in `synchronize'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/utils.rb:130:in `module_include'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/dartsass-sprockets-3.1.0/lib/sassc/rails/template.rb:40:in `call'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:84:in `call_processor'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
        	from org/jruby/RubyArray.java:2065:in `reverse_each'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `call_processors'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:22:in `block in CompositeProcessor'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:33:in `call'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:84:in `call_processor'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
        	from org/jruby/RubyArray.java:2065:in `reverse_each'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `call_processors'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:186:in `load_from_unloaded'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:59:in `block in load'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:43:in `load'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `block in load'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `load'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/bundle.rb:27:in `call'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:84:in `call_processor'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
        	from org/jruby/RubyArray.java:2065:in `reverse_each'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `call_processors'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:186:in `load_from_unloaded'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:59:in `block in load'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:43:in `load'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `block in load'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `load'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/base.rb:81:in `find_asset'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/base.rb:119:in `[]'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:358:in `find_asset'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:330:in `asset_path'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:103:in `block in resolve_asset_path'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:243:in `block in resolve_asset'
        	from org/jruby/RubyEnumerable.java:645:in `detect'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:242:in `resolve_asset'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:102:in `resolve_asset_path'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:80:in `compute_asset_path'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/helpers/asset_url_helper.rb:203:in `asset_path'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/helpers/asset_url_helper.rb:348:in `stylesheet_path'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/helpers/asset_tag_helper.rb:161:in `block in stylesheet_link_tag'
        	from org/jruby/RubyArray.java:2805:in `map'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/helpers/asset_tag_helper.rb:160:in `stylesheet_link_tag'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:186:in `block in stylesheet_link_tag'
        	from org/jruby/RubyArray.java:2805:in `map'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:184:in `stylesheet_link_tag'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/app/views/shared/_head.html.erb:5:in `_app_views_shared__head_html_erb__597805886_5404'
        	from org/jruby/RubyKernel.java:2232:in `public_send'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/base.rb:247:in `_run'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/template.rb:154:in `block in render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `block in instrument'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/activesupport-6.1.7.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `instrument'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/template.rb:345:in `instrument_render_template'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/template.rb:152:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `block in instrument'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/activesupport-6.1.7.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `instrument'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/partial_renderer.rb:271:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/renderer.rb:22:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/helpers/rendering_helper.rb:38:in `block in render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/base.rb:273:in `in_rendering_context'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/helpers/rendering_helper.rb:34:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/test_case.rb:198:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/app/views/layouts/pipelines.html.erb:4:in `_app_views_layouts_pipelines_html_erb___93287500_5400'
        	from org/jruby/RubyKernel.java:2232:in `public_send'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/base.rb:247:in `_run'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/template.rb:154:in `block in render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `block in instrument'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/activesupport-6.1.7.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `instrument'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/template.rb:345:in `instrument_render_template'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/template.rb:152:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/template_renderer.rb:72:in `block in render_with_layout'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `block in instrument'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/activesupport-6.1.7.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `instrument'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/template_renderer.rb:11:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/renderer/renderer.rb:22:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/helpers/rendering_helper.rb:38:in `block in render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/base.rb:273:in `in_rendering_context'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/helpers/rendering_helper.rb:34:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/test_case.rb:198:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/actionview-6.1.7.7/lib/action_view/test_case.rb:124:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-rails-6.1.2/lib/rspec/rails/example/view_example_group.rb:69:in `render'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/spec/views/layouts/pipelines_html_spec.rb:180:in `block in <main>'
        	from org/jruby/RubyBasicObject.java:2620:in `instance_exec'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:263:in `block in run'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:486:in `block in run'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:352:in `call'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-rails-6.1.2/lib/rspec/rails/adapters.rb:75:in `block in MinitestLifecycleAdapter'
        	from org/jruby/RubyBasicObject.java:2620:in `instance_exec'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:457:in `instance_exec'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:390:in `execute_with'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:628:in `block in run_around_example_hooks_for'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:352:in `call'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:486:in `run'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:259:in `run'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
        	from org/jruby/RubyArray.java:2805:in `map'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:651:in `run_examples'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:607:in `run'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `block in run'
        	from org/jruby/RubyArray.java:2805:in `map'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `run'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `block in run'
        	from org/jruby/RubyArray.java:2805:in `map'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `run'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:121:in `block in run_specs'
        	from org/jruby/RubyArray.java:2805:in `map'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:121:in `block in run_specs'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/configuration.rb:2091:in `with_suite_hooks'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/reporter.rb:74:in `report'
        	from /go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:115:in `run_specs'
        	
        	          ╷
        1 │ @import "sassc-embedded-import:/go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/node_modules/foundation-sites/scss/../_vendor/sassy-lists/stylesheets/helpers/_missing-dependencies.scss";
          │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ╵
          sassc-embedded-import:file:///go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/node_modules/foundation-sites/_vendor/sassy-lists/stylesheets/helpers/missing-dependencies 1:9  @import
          sassc-embedded-import:/go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/node_modules/foundation-sites/scss/foundation.scss 10:9                                                @import
          sassc-embedded-import:file:///go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/app/assets/new_stylesheets/shared/foundation-sites/scss/foundation 1:9                          @import
          sassc-embedded-import:/go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/app/assets/new_stylesheets/shared/_mixins.scss 21:9                                                    @import
          sassc-embedded-import:file:///go/pipelines/build-linux/server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/shared/mixins 1:9                                                        @import
          ../../../../../../../../app/assets/stylesheets/application.scss 33:9                                                                                                                        root stylesheet
```

**Comment by ntkme** [comment]
@chadlwilson Can you please try if https://github.com/sass-contrib/sassc-embedded-shim-ruby/commit/efbba5f659a61a56b7dbf448f48c3ca053593bcd fixes it?

**Comment by chadlwilson** [comment]
Thanks @ntkme - I tried to give this a quick go in https://github.com/gocd/gocd/pull/12668 but started getting 

```
LoadError:
  no such file to load -- sassc
 ```
 
 ... which is probably a different problem on our side with how things are being loaded. Will need a bit more time later to try and figure out what stupid thing I am/we are doing.

**Comment by ntkme** [comment]
@chadlwilson Use the git reference would not work out of box because this project has `sassc` as a git submodule. You need to either clone the submodule or you can try manually apply the diff to exist gem installation.

**Comment by chadlwilson** [comment]
Ahh. OK, cool, got it.

**Comment by ntkme** [comment]
Seems like you can just add `submodules: true`:

``` ruby
    gem 'sassc-embedded', github: 'sass-contrib/sassc-embedded-shim-ruby', ref: 'unique-import-id', submodules: true
```

https://bundler.io/guides/git.html

**Comment by chadlwilson** [comment]
Ahh ok, yeah now that leads to a different problem specific to the way Gradle (a sour Java build tool) is being used to cache gems due to the symlinks in there (definitely our problem) so I'll try locally later rather than relying on the pipeline.

```
> Failed to store cache entry 547f1e152d50134c8ad9569ca503efb2 for task ':server:initializeRailsGems': Could not pack tree '$1': Couldn't read content of file '/go/pipelines/build-linux-pull_12668/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/bundler/gems/sassc-embedded-shim-ruby-efbba5f659a6/vendor/github.com/rails/sprockets/test/fixtures/errors/symlink'
```

**Comment by ntkme** [comment]
@chadlwilson The reproduction is kind of surprising https://github.com/sass-contrib/sassc-embedded-shim-ruby/commit/b51c43d073258b2d926a6dcf39bb6a36dcd03af0. I've merged #90 and 1.74.1 will be released by GitHub Action very soon.

Hopefully this will make it easier for you to test, and please let me know if there is any other issue.

**Comment by ntkme** [comment]
`1.74.1` is available: https://rubygems.org/gems/sassc-embedded/versions/1.74.1

**Comment by chadlwilson** [comment]
Oh wow, fantastic - no idea how you figured that one out!

Perfect, that's working fine locally. Will merge and double check it's good on the always unpredictable JRuby-on-Windows but let's assume it's fine. 😅
